### PR TITLE
Add parsing of SMPTE2038

### PR DESCRIPTION
**Pull request by Loic-Bvn-A**
Hello, here's a PR to add a SMPTE2038 parser, best regards.

### CODE REVIEW

**Comment by EricBerendsen** [comment]
Hi, this looks very interesting. Not something I have seen before. Can you provide me with a sample test stream and documentation? (If it is confidential you can send it by email)

**Comment by Loic-Bvn-A** [comment]
Hi, as these informations are confidential, can you provide your email address in order to send you the files? Thank you.

**Comment by EricBerendsen** [comment]
You can use info [at] digitalekabeltelevisie.nl  , thanks.

**Review by EricBerendsen — CHANGES_REQUESTED** [review]
Nice work. I do have some comments, please have a look at them.

**Comment by Loic-Bvn-A** [comment]
Hi, thank you for all your feedbacks and suggestions.

I submitted a commit taking your requests into account.

Best regards.

**Comment by EricBerendsen** [comment]
Hi, thank you very much for this addition to DVB inspector.

**Pull request merged**
