### PR TITLE
add AVS3 from DVB NGVC actibvity

### PR DESCRIPTION
**Pull request by paulhiggs**
This PR adds functionality related to the use of AVS3 coded video in a DVB transport stream (descriptor, components and stream type) according to the updated [DVB A001r20 clauses 4.1 and 5.16 ](https://dvb.org/wp-content/uploads/2022/02/A001r20_Use-of-Video-and-Audio-Coding-in-Broadcast-and-Broadband-Applications_Draft_TS_101-154-v281_July-2022.pdf) | ETSI TS 101 154 including Next Generation Video Codecs (NGVC) and EN 300 468 (soon to be published)

### CODE REVIEW

**Comment by paulhiggs** [comment]
This is all published by DVB in Bluebook A001 (precursor to the next revision  on ETSI TS 101 154) as well as T/AI 109.2 (video coding) and T/AI 109.6 (systems specifications) published by the AVS Workgroup of China.

**Comment by EricBerendsen** [comment]
Hi Paul,

I have now merged your PR into the master branch of DVB inspector. I made two small changes;

1. I added the option in settings for Private Data Specifier Default for 0x41565356, "Audio Video Coding Standard Workgroup of China (AVS3)", so the descriptor can still be parsed when the PrivateDataSpecifierDescriptor is ommited. 
2. I created a fresh complete version of private_data_spec_id.csv based on https://www.dvbservices.com/identifiers/private_data_spec_id It contains some extra new entries.

One more question, according to T/AI 109.6 9.2.1 Stream identification it says;
"AVS3 video stream should be [...] identified by the value of stream_type field (0xD4) allocated in the program map table."
So I think a line should be added to getStreamTypeString(final int tag){ (in Utils.java line 833) to give a give a correct description in the PMT components loop, something like 
case 0xD4: return "User Private / AVS3";

Also, I would be very interested to get some test streams for AVS3, if possible.

Thank you again for your contribution

**Comment by paulhiggs** [comment]
Thanks for merging this. I am not sure about the statement 'so the descriptor can still be parsed when the PrivateDataSpecifierDescriptor is ommited' as many privately defined descriptors can use the same descriptor tag (209, 0xD1).
The descriptor should only be parsed as an AVS3_video_descriptor if the most recent private_data_specifier_descriptor contained `private_data_specifier= 0x41565356`.
If this not done, any other entity that defines a private descriptor with that tag `0xD1` will be incorrectly analyzed.

We have just finalized the V&V sequences for DVB including AVS3 in a transport stream, I can make a couple of those available shortly.

**Comment by EricBerendsen** [comment]
> Thanks for merging this. I am not sure about the statement 'so the descriptor can still be parsed when the PrivateDataSpecifierDescriptor is ommited' as many privately defined descriptors can use the same descriptor tag (209, 0xD1). The descriptor should only be parsed as an AVS3_video_descriptor if the most recent private_data_specifier_descriptor contained `private_data_specifier= 0x41565356`. If this not done, any other entity that defines a private descriptor with that tag `0xD1` will be incorrectly analyzed.

Correct, that is how it is supposed to work. And that is also the normal behaviour of DVB Inspector when Private DataSpecifier Default is set to 0;

image

However, some operators omit the private_data_specifier (maybe because they control the receiving devices, and know it will always be their own private data).  If you have a stream like that, you can force DVB Inspector to interpret 'unknown' private descriptors according the a certain private_data_specifier (if supported)

[TSDuck](https://tsduck.io/download/docs/tsduck.pdf) has a similar feature with the option  --default-pds;

image

> We have just finalized the V&V sequences for DVB including AVS3 in a transport stream, I can make a couple of those available shortly.

That would be nice. From the documentation I think AVS uses some features of PESHeader (like pes_extension_flag_2 ==1) that DVB Inspector does not support yet  Would be good to add.

**Comment by paulhiggs** [comment]
Just noticing that this issue is still open, even though all the code is updated.
The DVB reference bitstreams are available on their [Vaidation & Verification page](https://dvb.org/specifications/verification-validation/)

**Pull request merged**
