### PR TITLE
Slow file load on large amount of section_syntax_indicator=0 private sections

### PR DESCRIPTION
**Pull request by avrecko**
A file was loading very slow with DVBInspector. The slowdown was due to iteration to find a section. I've change it to use HashMap lookup instead of iteration. Now file loads with normal speed. Used LinkedHashMap to preserve insertion order.

### CODE REVIEW

**Comment by EricBerendsen** [comment]
Looks interesting. Wondering, what type of file/data will cause slow download? Maybe you could provide a test sample?

Also, did not have time to test this yet, would it increase memory usage? Looks good, just need to find a bit more time to review.

**Comment by avrecko** [comment]
I am using simple private sections to store some extra metadata about the
video frame inside the ts file. It is a very rare use case. If there are
100K video frames there are going to be 100K private sections.

So for every video frame it will iterate over frame count - 1 worth of
simple private sections. Not a big deal if there are just a few private
sections. But unusably slow with large counts of private sections.

For a test sample. I think the easiest is just to make a test file with
something like 100K of private sections. Let me know if you'd like me to
make this file for you.

In terms of memory usage. There is just some more memory usage due to
LinkedHashMap's internal data structure over a List implementation. I think
for 99.9% of cases the memory increase is going to be negligible as I don't
think it is very common to have huge amounts of simple private sections.

V V tor., 1. nov. 2022 ob 20:31 je oseba Eric Berendsen <
***@***.***> napisala:

**Comment by EricBerendsen** [comment]
Merged this into master.

Did some testing with file from https://tsduck.io/streams/?name=russia-t2mi-scte35 (4.9 GB)

On my machine loading went from over 35 minutes to 1 minute 42 seconds. Very nice!

Thank you again for this improvement!

**Comment by avrecko** [comment]
My pleasure. DVBInspector is awesome!

V V ned., 6. nov. 2022 ob 17:51 je oseba Eric Berendsen <
***@***.***> napisala:

**Pull request merged**
