### PR TITLE
Improve JPEG-XS parsing

### PR DESCRIPTION
**Pull request by simon-provost**
Hi, I've added code to parse the JPEG-XS video descriptor and JPEG-XS elementary stream header (which follows a standard PES header).
You can get from [here](https://riedelcommunications-my.sharepoint.com/:v:/g/personal/simon_provost_riedel_net/EcIS_huj4T5Dk-wvv3oAuOEByg-LZtCnyVgViOwTyHKlzg) an mpeg file containing a JPEG-XS stream, which can be used to view the results of the changes. The 2 changes can be seen by navigating
1) Transport Stream 0 -> PSI -> PMTs -> program: 0x1 -> TableType -> components -> component -> Descriptor -> JPEG-XS Descriptor
Under the JPEG-XS Descriptor, you'll see all decoded fields of the descriptor.
2) Transport Stream 0 -> PIDs -> pid: 0x64 (100) ->Transport packets -> [0..9999] -> [1300..1399] -> transport_packet [3138]
On selecting the transport packet, in the right frame, you'll see, in yellow, the JPEG-XS header. There is also a JXES Header added in the tree node under the transport_packet.[](url)

Regards
Simon

### CODE REVIEW

**Comment by EricBerendsen** [comment]
Hi Simon,

Thank you very much. Not just a feature request, but a complete implementation, with test data! 

JPEG-XS  is completely new to me, and there is quit a bit of code, so I will need some time to have a look at it.

First remark, I am trying to keep the UX consistent, and for all PES streams parsing is an extra step (mainly because of memory).  In your implementation the JPEG-XS header is always added to the TSPacket. That may not be the place where users expect it, and it also takes a bit of searching (you may have to expand a lot of node to find a payload start packet) I think it makes more sense to add this info to the a JPEG-XS PES Packet.

Question, what platform do you use, Linux? On windows the colour you selected is bit hard to read;
image

Discovered different platforms use different BG colours. Should check for that more,

**Comment by simon-provost** [comment]
Thanks for the quick feedback.
About the color, yes, I'm using Linux. I tried to find something which worked relatively well with both light and dark themes. It looks like your background color is about midway between my light and dark backgrounds. I'll use your screenshot to find something better.
About your other point, sorry, I'm not yet that familiar with your application. But could you give me a little bit more details about where you would rather see the information?
Thanks

**Comment by EricBerendsen** [comment]
Have a look at [https://www.digitalekabeltelevisie.nl/dvb_inspector/pids.shtml](https://www.digitalekabeltelevisie.nl/dvb_inspector/pids.shtml) to see how PES Data is handled in DVB Inspector. It is not handled by default. Only when a PID node is selected, and "parse data" is selected from the popup menu the file is re-read, and that PES Data is interpreted. A node with PES Data is added.

Example:

image

This way it is also possible to show graphs with Frame type and/or frame size. (I think I understand that JPEG-XS uses fixed frame size and frame type, so there is not much added value in that.

Implementing this solution is a bit more complicated, because it means creating a special JPEGXSHandler for parsing, a JpegXsPESDataField, etc.  I can understand you did not want to use this approach.

If you want I can use your code and refactor it to fit into the GUI people are used to. Just let me know.

**Comment by simon-provost** [comment]
Thanks for the comments. I'll try and see if I can implement all those changes and get back to you.

**Comment by simon-provost** [comment]
Did the changes. Hope I got it right. Actually feels much more inline with the rest of the code now.

**Review by EricBerendsen — APPROVED** [review]
Hi Simon, great Job. The only (very minor) thing that I will fix later is that I will move JpegXsDataField.java and JpegXsHandler to their own package data.mpeg.video.jpegxs.  The stuff in data.mpeg.video should be in data.mpeg.video262 (It was written when DVB Inspector supported only MPEG2 video)

Thanks again, and if you have any other comments/suggestions do not hesitate to contact me. It is not required to provide a full implementation...

**Comment by simon-provost** [comment]
That's great, many thanks. Was happy to help :)

**Pull request merged**
